### PR TITLE
For comparison

### PR DESCRIPTION
**Pull request by maelle**
And here's what R told me

```r
> testApp("inst/colocr_app")
Running one_image.R setInputs(app$setInputs(threshold = 90)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(clean = 8)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(fill = 8)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(shrink = 6)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(roi_num = 2)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(roi_num = 3)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(fill = 5)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(clean = 10)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(shrink = 8)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(fill = 10)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
two_images.R setInputs(app$setInputs(threshold = 90)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.
setInputs(app$setInputs(roi_num = 3)): Server did not update any output values within 3 seconds. If this is expected, use `wait_=FALSE, values_=FALSE`, or increase the value of timeout_.

==== Comparing one_image... 
  No existing snapshots at one_image-expected/. This is a first run of tests.

Updating baseline results at inst/colocr_app/tests/one_image-expected...
Renaming inst/colocr_app/tests/one_image-current
      => inst/colocr_app/tests/one_image-expected.
==== Comparing two_images... 
  No existing snapshots at two_images-expected/. This is a first run of tests.

Updating baseline results at inst/colocr_app/tests/two_images-expected...
Renaming inst/colocr_app/tests/two_images-current
      => inst/colocr_app/tests/two_images-expected.
```

cf https://github.com/ropensci/onboarding/issues/243#issuecomment-423421173

### CODE REVIEW

**Comment by maelle** [comment]
Am going to run the app manually now

**Comment by maelle** [comment]
image

All I can do for now, good luck!

**Comment by maelle** [comment]
Can you give me minimal code using imager? Then we could open an issue in their repo if that's the problem

**Comment by maelle** [comment]
Or you can switch to `magick` by @jeroen if it appears that `imager` is the problem. 😉

**Comment by MahShaaban** [comment]
Thanks @maelle. I wonder what happen when you run the tests again after the expected images are created. This is what I meant by running `shinytest::testApp()` again. Sorry for not being clear in my suggestion.

**Comment by maelle** [comment]
I cant try now but I'd get the same results again I think, since I alsp got them when running the app manually.

**Pull request closed without merging**
